sudo: required
dist: trusty
git:
  depth: 1
services:
  - docker
language: generic
cache:
  apt: true
  directories:
    - $HOME/.composer/cache
before_install:
  - docker version
  - docker-compose version
before_script:
  - docker-compose up --build --abort-on-container-exit
script: docker-compose run cli bash -c "php -r \"echo file_get_contents('http://web');\""
after_failure:
  - docker ps -s
